apiVersion: vance.io/v1alpha1
kind: Connector
metadata:
  name: webhook-sample
spec:
  # TODO(user): Add fields here
  type: http
  image: tomcat:8.0.18-jre8
  scalerSpec:
    metadata:
      host: myhost.com
      svcPort: 8080
      maxReplica: 30
      pendingRequests: 20
