# To configure the environment locally to test the website, check out
# https://help.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll

title: cdk-go for Vance
baseurl: "/cdk-go"
url: "https://linkall-labs.github.io"
remote_theme: just-the-docs/just-the-docs
plugins:
    - jemoji

search_enabled: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/linkall-labs/cdk-go"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

aux_links:
    "GitHub Repository":
        - "https://github.com/linkall-labs/cdk-go"
    "Linkall home":
        - "https://linkall.com/"
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 Linkall, Inc."

compress_html:
    clippings: all
    comments: all
    endings: all
    startings: []
    blanklines: false
    profile: false
    # ignore:
    #   envs: all
